'
ScopeLift/l2-flexible-voting pull request #93
Opened 2023-12-19 17:56 UTC by alexkeating

2023-12-19 17:56 UTC, alexkeating commented
Current dependencies on/for this PR:
* `main`
  * **PR #93** <a href="https://app.graphite.dev/github/pr/ScopeLift/l2-flexible-voting/93?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/ScopeLift/l2-flexible-voting/93?utm_source=stack-comment).

2024-01-19 20:25 UTC, wildmolasses requested changes
a few nits otherwise lgtm

2024-01-19 20:25 UTC, wildmolasses commented on src/L2CountingFractional.sol
> +    require(_newWeight <= totalWeight, "GovernorCountingFractional: vote would exceed weight");
```suggestion
    require(_newWeight <= totalWeight, "L2CountingFractional: vote would exceed weight");
```

2024-01-19 20:25 UTC, wildmolasses commented on src/L2CountingFractional.sol
> +    require(voteData.length == 48, "GovernorCountingFractional: invalid voteData");
```suggestion
    require(voteData.length == 48, "L2CountingFractional: invalid voteData");
```

2024-01-19 20:25 UTC, wildmolasses commented on src/L2CountingFractional.sol
> +      revert("GovernorCountingFractional: invalid support value, must be included in VoteType enum");
```suggestion
      revert("L2CountingFractional: invalid support value, must be included in VoteType enum");
```

2024-01-19 20:25 UTC, wildmolasses commented on src/L2CountingFractional.sol
> +      "GovernorCountingFractional: vote would exceed weight"
```suggestion
      "L2CountingFractional: vote would exceed weight"
```

2024-01-19 20:25 UTC, wildmolasses commented on src/L2CountingFractional.sol
> +      revert("GovernorCountingFractional: all weight cast");
```suggestion
      revert("L2CountingFractional: all weight cast");
```

2024-01-19 20:25 UTC, wildmolasses commented on src/L2CountingFractional.sol
> +  mapping(address => uint128) public fractionalVoteNonce;
unneeded, can remove

2024-01-22 14:19 UTC, alexkeating commented on src/L2VoteAggregator.sol
> -  /// @dev Data structure to store vote preferences expressed by depositors.
Good point, I think we are okay with that for now

2024-01-25 19:08 UTC, merged